export default
`
# **史蒂芬·保罗·乔布斯**

（英语：Steven Paul Jobs，1955年2月24日－2011年10月5日），[[2\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-2)[[3\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-3)通称**史蒂夫·乔布斯**（英语：Steve Jobs），是一名美国[发明家](https://zh.wikipedia.org/wiki/發明家)、[企业家](https://zh.wikipedia.org/wiki/企业家)、[[4\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-4)营销家[[5\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-5)，[苹果公司](https://zh.wikipedia.org/wiki/蘋果公司)的联合创始人之一，曾任[董事长](https://zh.wikipedia.org/wiki/董事長)及[首席执行官](https://zh.wikipedia.org/wiki/行政總裁)职位，[NeXT](https://zh.wikipedia.org/wiki/NeXT)创办人及首席执行官，也是[皮克斯动画](https://zh.wikipedia.org/wiki/皮克斯动画工作室)的创办人并曾任首席执行官，2006年为[华特迪士尼公司](https://zh.wikipedia.org/wiki/华特迪士尼公司)的董事会成员[[6\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-6)[[7\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-stevejobs-7)。2017年9月苹果发布会举行的地方，以他命名为 Steve Jobs Theater 。

乔布斯在1970年代末与苹果公司另一始创人[斯蒂夫·沃兹尼亚克](https://zh.wikipedia.org/wiki/史蒂夫·沃茲尼克)及首任投资者[迈克·马库拉](https://zh.wikipedia.org/wiki/迈克·马库拉)协同其他人设计、开发及销售[Apple II](https://zh.wikipedia.org/wiki/Apple_II)系列。在1980年代初，乔布斯是最早看到施乐帕洛奥图中心（Xerox PARC）的[鼠标](https://zh.wikipedia.org/wiki/滑鼠)驱动图形用户界面的商业潜力，并将其应用于[Apple Lisa](https://zh.wikipedia.org/wiki/Apple_Lisa)及一年后的[麦金塔电脑](https://zh.wikipedia.org/wiki/麦金塔电脑)。[[8\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-8) 1985年，在董事会的斗争失势后，乔布斯离开苹果公司及成立了[NeXT公司](https://zh.wikipedia.org/wiki/NeXT)(一间电脑平台开发公司，专门从事高等教育及商业市场)在1986年，他收购了[卢卡斯影业](https://zh.wikipedia.org/wiki/卢卡斯影业)的电脑绘图部门，成立了[皮克斯](https://zh.wikipedia.org/wiki/皮克斯)（Pixar）。[[9\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-Pixar_History_1986-9)他被誉为《[玩具总动员](https://zh.wikipedia.org/wiki/玩具总动员)》（1995年）的运行制片人。他一直担任皮克斯动画的首席执行官并持有50.1%的股份，直到公司在2006年被[华特迪士尼公司](https://zh.wikipedia.org/wiki/华特迪士尼公司)收购，此项收购使乔布斯成为[迪士尼](https://zh.wikipedia.org/wiki/迪士尼)公司的最大个人股东（有7.4%的股份）及董事会成员。[[10\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-Apple_2006-10) 在1996年，[苹果公司](https://zh.wikipedia.org/wiki/蘋果公司)董事会决议买下[NeXT](https://zh.wikipedia.org/wiki/NeXT)公司，把乔布斯带回他参与创立，却正在垂死边缘的[苹果公司](https://zh.wikipedia.org/wiki/蘋果公司)担任临时CEO。他在2000年起成为正式CEO，带领苹果辉煌的[iPod](https://zh.wikipedia.org/wiki/IPod)、[iPhone](https://zh.wikipedia.org/wiki/IPhone)、[iPad](https://zh.wikipedia.org/wiki/IPad)时代的到来。[[11\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-DNA200905-11) 从2003年10月起，乔布斯与[胰腺](https://zh.wikipedia.org/wiki/胰腺)[神经内分泌肿瘤](https://zh.wikipedia.org/wiki/神經內分泌腫瘤)奋战了8年，[[12\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-12)最终于2011年8月辞任首席执行官一职，在他第3次病假期间，乔布斯当选为苹果公司的董事长。

在他生活的年代里，乔布斯被认为是电脑业界与娱乐业界的标志性人物，同时人们也把他视作麦金塔电脑、[iPod](https://zh.wikipedia.org/wiki/IPod)、[iPhone](https://zh.wikipedia.org/wiki/IPhone)、[iPad](https://zh.wikipedia.org/wiki/IPad)等知名数字产品的缔造者。他亦曾七次登上《[时代杂志](https://zh.wikipedia.org/wiki/時代雜誌)》的封面，被认为是当时全球最为成功的商人之一。2007年，乔布斯被《[财富](https://zh.wikipedia.org/wiki/財富_(雜誌))》杂志评为了年度最强有力商人。[[13\\]](https://zh.wikipedia.org/wiki/史蒂夫·乔布斯#cite_note-Steve_Jobs_is_named_Number_One_most_powerful_businessman_by_Fortune-13)乔布斯的生涯极大地影响了[硅谷](https://zh.wikipedia.org/wiki/硅谷)风险创业的传奇，他将[美学](https://zh.wikipedia.org/wiki/美學)至上的设计理念在世界上推广开。他对简约及便利设计的推崇为他赢得了许多忠实追随者。[[14\\]](
`;